# Site settings
title: wikysμ ν¬νΈν΄λ¦¬μ¤ # π‘ μ—¬κΈ°μ— ν¬νΈν΄λ¦¬μ¤ μ λ©
name: wikys # π‘ μ—¬κΈ°μ— λ³ΈμΈ μ΄λ¦„
description: >- # π‘ μ—¬κΈ°μ— ν• μ¤„ μ†κ°
  λ…Όλ¦¬μ™€ λ°μ΄ν„°λ΅ κµμ΅μ λ―Έλλ¥Ό μ„¤κ³„ν•λ” AI κµμ΅ κΈ°νμ, wikysμ…λ‹λ‹¤.